### ISSUE TITLE
releasing connections from the pool

### ISSUE THREAD

**Issue by melbardis** [joeandaverde/tinypg#10]
hi

not sure if this is an issue or not..

it appears that when doing a transactions, new connections are obtained from  pg.Pool which causes the pool to emit an 'acquire' event. However a release is never done which would emit the 'remove' event. This behavior was observed by adding some console.log debug messages in the _remove & connect functions in "node_modules\pg-pool\index.js".

the reason i wanted the acquire/remove was so i could add a notice handler on the pool to allow for sql debug output to be seen. with the code below i get the notice events.

```javascript
const TinyPg = require('tinypg').TinyPg;

const db = new TinyPg({
    connection_string: 'postgres://ww_info:test123@localhost:5432/ww_info?sslmode=disable',
    root_dir: __dirname + '\\..\\sql'
});

function doNotice(notice) {
    console.log(`Notice: [%s] %s`, notice.severity, notice.message);
    console.log(`        %s`, notice.where);
}

db.pool.on('acquire', client => {
    // Note: June 20, 2018 -- off is done to prevent growing number of event handlers! 'remove' event does not appear to work!
    client.off('notice', doNotice);
    client.on('notice', doNotice);
})


// Note: June 20, 2018 -- does not appear to work (never called)
db.pool.on('remove', client => {
    console.log(`Remove: db=%o`, client)
    client.off('notice', doNotice);
})
`
regards

eric

**Comment by joeandaverde** [comment]
Can you verify your intent? I think `remove` will only be called when the client has been removed from the pool. This occurs after the client has been idle for a certain amount of time. It is configurable.

**Comment by melbardis** [comment]
hi

i started down this path because i wanted to log the output from sql's
RAISE statement, which comes in as a 'notice' event when you use pg &
pg-monitor.

i figured i needed to add the event handler on the client object, so i did
that on the 'acquire' event. worked great except the handlers never went
away and a new one got added for every transaction ... so number of outputs
for the same notice kept growing, appeared same client connection was being
used

so i figured i would remove the handler on the 'remove' event but never got
the event ... so i started to explore ...

i got around it by doing the 'off' method before the 'on' method and am
happy with the results

so far i am using to test my database procedures (jasmine & tinypg)  and
only use one connection

but it got me thinking, are these connections released when doing larger
number of simultaneous connections??
especially since i get the 'acquire' event for every transaction and no
'remove' event??

i suppose a load test with a few hundred simultaneous queries would be in
order ..

regards

ericc

**Comment by joeandaverde** [comment]
The transaction function will acquire and keep the same client for all subsequent queries. After the transaction promise completes it should be released back to the pool. If multiple transactions are started (and not nested) they will acquire new clients. Does this accurately describe your understanding?

**Comment by melbardis** [comment]
that's how i thought it worked, but i don't think the release is being done
since the pg.pool function _remove is not being called (pg-pool)


i got it from the pg docs:

pool.on('acquire', (client: Client) => void) => void

Whenever the a client is checked out from the pool the pool will emit the
acquire event with the client that was acquired.
pool.on('remove', (client: Client) => void) => void

Whenever a client is closed & removed from the pool the pool will emit the
remove event.

**Comment by joeandaverde** [comment]
Are you able to submit a script that reproduces the issue?

**Comment by joeandaverde** [comment]
Here's my attempt to reproduce:

```const TinyPg = require('../dist').TinyPg

const db = new TinyPg({
   connection_string: 'postgres://postgres@localhost:5432/mydb?sslmode=disable',
   root_dir: __dirname + '/sql_files'
})

function doNotice(notice) {
   console.log(`Notice: [%s] %s`, notice.severity, notice.message);
   console.log(`        %s`, notice.where);
}

db.pool.on('acquire', client => {
  console.log('acquire')
})

db.pool.on('remove', client => {
   console.log(`Remove: db=%o`)
})

db.transaction(txdb => {
   return txdb.sql('fetch_user_by_name', {
      name: 'Joe',
   })
   .then(res => {
      console.log(res)
   })
   .catch(error => {
      console.log(error)
   })
})
```

and the output:

```
acquire
{ row_count: 0, rows: [], command: 'SELECT' }
Remove
```

**Comment by melbardis** [comment]
strange ...

i just tried your db.transaction (different procedure) and no remove
event...
could our node packages be different? i should have the latest ... i got
all the libraries over the last couple of days ..

i am attaching my package-lock.json

funny, under tinypg, the only pg dependency is pg-format ??

**Comment by joeandaverde** [comment]
Node Postgres is a peer dependency. That way you can upgrade if any security issues come out and I do t get to it right away.

**Comment by melbardis** [comment]
then i wonder why it works for you, i am using node 10.4.1 on windows 7

on another topic: in the sql files can one have more than one sql
statement, for example 2x [select someprocedure()] or multiple inserts??

**Comment by melbardis** [comment]
something interesting ...

trace output - interesting parts are in bold large font ...
----------------------------------------------------------------

Executing 2 defined specs...

Test Suites & Specs:

1. resetDB testing
  tinypg transaction +0ms
  tinypg getClient [total=0,waiting=0,idle=0] +1ms
  tinypg:pool connecting new client +0ms
  tinypg:pool connecting new client +1ms
  tinypg:pool new client connected +28ms
  tinypg BEGIN transaction +32ms
  tinypg sql resetDB +2ms
  tinypg performDbCall resetDB +0ms
  tinypg getClient (transaction) +1ms
Query:  [resetDB] SELECT resetDB();

insert into types (is_type, name) values ('obj', 'a') returning *;
insert into types (is_type, name) values ('obj', 'b') returning *;
insert into types (is_type, name) values ('obj', 'c') returning *;
insert into types (is_type, name) values ('obj', 'd') returning *;
insert into types (is_type, name) values ('obj', 'e') ;

-- select resetDB();
-- select 1;
  tinypg executing resetDB +1ms
  tinypg execute result resetDB +52ms
context={ id: '6e3bd20b-6127-4fb4-8f14-7c4e4e5b4df0',
  sql:
   'SELECT resetDB();\r\n\r\ninsert into types (is_type, name) values
(\'obj\', \'a\') returning *;\r\ninsert into types (is_type, n
ame) values (\'obj\', \'b\') returning *;\r\ninsert into types
(is_type, name) values (\'obj\', \'c\') returning *;\r\ninsert into t
ypes (is_type, name) values (\'obj\', \'d\') returning *;\r\ninsert
into types (is_type, name) values (\'obj\', \'e\') ;\r\n\r\n-- s
elect resetDB();\r\n-- select 1;',
  start: 1529512307557,
  name: 'resetDB',
  params: {},
  end: 1529512307612,
  duration: 55,
  error: null,
  data:
   { row_count: undefined, rows: undefined, command: undefined } }
Result: [resetDB] (55ms ) undefined row(s)
      = " "
  *tinypg COMMIT transaction +6ms
  tinypg RELEASE transaction client* Client { _events: { error:
[Function: idleListener] }, _eventsCount: 1, _maxListeners: undefined
, connectionParameters: ConnectionParameters { user: 'ww_info',
database: 'ww_info', port: 5432, host: 'localhost', password: 'test1
23', binary: false, ssl: false, client_encoding: '', replication:
undefined, isDomainSocket: false, application_name: undefined, fal
lback_application_name: undefined, statement_timeout: false }, user:
'ww_info', database: 'ww_info', port: 5432, host: 'localhost',
password: 'test123', replication: undefined, _types: TypeOverrides {
_types: { getTypeParser: [Function: getTypeParser], setTypePars
er: [Function: setTypeParser], arrayParser: [Object] }, text: {},
binary: {} }, _ending: false, _connecting: false, _connected: true
, _connectionError: false, connection: Connection { _events: {
newListener: [Function], connect: [Function], sslconnect: [Function],
 authenticationCleartextPassword: [Function],
authenticationMD5Password: [Function], readyForQuery: [Function], end:
[Function], not
ice: [Function], rowDescription: [Function], dataRow: [Function],
portalSuspended: [Function], emptyQuery: [Function], commandComple
te: [Function], parseComplete: [Function], copyInResponse: [Function],
copyData: [Function], notification: [Function], error: [Funct
ion: connectedErrorHandler] }, _eventsCount: 18, _maxListeners:
undefined, stream: Socket { connecting: false, _hadError: false, _ha
ndle: [TCP], _parent: null, _host: 'localhost', _readableState:
[ReadableState], readable: true, _events: [Object], _eventsCount: 5,
 _maxListeners: undefined, _writableState: [WritableState], writable:
true, allowHalfOpen: false, _sockname: null, _pendingData: nul
l, _pendingEncoding: '', server: null, _server: null,
[Symbol(asyncId)]: 45, [Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: nul
l, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }, _keepAlive:
false, lastBuffer: false, lastOffset: 0, buffer: null, offset:
 1, encoding: 'utf8', parsedStatements: {}, writer: { size: 1024,
buffer: <Buffer 51 00 00 00 0b 43 4f 4d 4d 49 54 00 72 65 73 65 74
 44 42 28 29 3b 0d 0a 0d 0a 69 6e 73 65 72 74 20 69 6e 74 6f 20 74 79
70 65 73 20 28 69 73 5f 74 79 ... >, offset: 5, headerPosition
: 0, lastEnd: 0 }, ssl: false, _ending: false, _mode: 0, _emitMessage:
false, _reader: { offset: 18, lastChunk: false, chunk: <Buffe
r 43 00 00 00 0b 43 4f 4d 4d 49 54 00 5a 00 00 00 05 49>, chunkLength:
18, headerSize: 1, lengthPadding: -4, header: 90 } }, queryQu
eue: [], binary: false, processID: 3896, secretKey: -690201510, ssl:
false, release: [Function], activeQuery: null, readyForQuery: t
rue, hasExecuted: true } +16ms********************** release in
pg-pool err=undefined this.endig=false
  tinypg:pool pulse queue +103ms*
  tinypg:pool no queued requests +4ms
   ? should be error free

2. Test type functions


------------------------------------------------------------------

tinypg code - tiny.js in transaction
-----------------------------------------------------------------

               const release = () => {
                    log('RELEASE transaction client %o', tx_client);
                    tx_client.release = release_ref;
                 *   tx_client.release(); // no args to release????*
                };


-----------------------------------------------------------------

pg-pool code i- ndex.js  in release
------------------------------------------------------------------

function release (client, err) {
    console.log(`********************* release in pg-pool err=${err}
this.endig=${this.ending}`);
  client.release = throwOnRelease
  if (err || this.ending) {
      console.log("*&&&&&&&&&&&&&&&& _remove called");
    this._remove(client)
    this._pulseQueue()
    return
  }



-----------------------------------------------------------------

**Comment by joeandaverde** [comment]
The format you describe doesn't seem to come through on the email chain.

Mind trying the web interface?

**Comment by melbardis** [comment]
yeah looks bad ...


a little better ... not many formatting options in this markup ... 
pdf of prev comment included
[releasing connections from the pool (#10).pdf](https://github.com/joeandaverde/tinypg/files/2120551/releasing.connections.from.the.pool.10.pdf)


trace output - interesting parts are in bold ...
----------------------------------------------------------------
Executing 2 defined specs...

Test Suites & Specs:

1. resetDB testing
  tinypg transaction +0ms
  tinypg getClient [total=0,waiting=0,idle=0] +1ms
  tinypg:pool connecting new client +0ms
  tinypg:pool connecting new client +1ms
  tinypg:pool new client connected +28ms
  tinypg BEGIN transaction +32ms
  tinypg sql resetDB +2ms
  tinypg performDbCall resetDB +0ms
  tinypg getClient (transaction) +1ms
Query:  [resetDB] SELECT resetDB();

insert into types (is_type, name) values ('obj', 'a') returning *;
insert into types (is_type, name) values ('obj', 'b') returning *;
insert into types (is_type, name) values ('obj', 'c') returning *;
insert into types (is_type, name) values ('obj', 'd') returning *;
insert into types (is_type, name) values ('obj', 'e') ;

-- select resetDB();
-- select 1;
  tinypg executing resetDB +1ms
  tinypg execute result resetDB +52ms
context={ id: '6e3bd20b-6127-4fb4-8f14-7c4e4e5b4df0',
  sql:
   'SELECT resetDB();\r\n\r\ninsert into types (is_type, name) values (\'obj\', \'a\') returning *;\r\ninsert into types (is_type, n
ame) values (\'obj\', \'b\') returning *;\r\ninsert into types (is_type, name) values (\'obj\', \'c\') returning *;\r\ninsert into t
ypes (is_type, name) values (\'obj\', \'d\') returning *;\r\ninsert into types (is_type, name) values (\'obj\', \'e\') ;\r\n\r\n-- s
elect resetDB();\r\n-- select 1;',
  start: 1529512307557,
  name: 'resetDB',
  params: {},
  end: 1529512307612,
  duration: 55,
  error: null,
  data:
   { row_count: undefined, rows: undefined, command: undefined } }
Result: [resetDB] (55ms ) undefined row(s)
      = " "
  **tinypg COMMIT transaction +6ms
  tinypg RELEASE transaction client** 
```javascript
Client { _events: { error: [Function: idleListener] }, _eventsCount: 1, _maxListeners: undefined
, connectionParameters: ConnectionParameters { user: 'ww_info', database: 'ww_info', port: 5432, host: 'localhost', password: 'test1
23', binary: false, ssl: false, client_encoding: '', replication: undefined, isDomainSocket: false, application_name: undefined, fal
lback_application_name: undefined, statement_timeout: false }, user: 'ww_info', database: 'ww_info', port: 5432, host: 'localhost',
password: 'test123', replication: undefined, _types: TypeOverrides { _types: { getTypeParser: [Function: getTypeParser], setTypePars
er: [Function: setTypeParser], arrayParser: [Object] }, text: {}, binary: {} }, _ending: false, _connecting: false, _connected: true
, _connectionError: false, connection: Connection { _events: { newListener: [Function], connect: [Function], sslconnect: [Function],
 authenticationCleartextPassword: [Function], authenticationMD5Password: [Function], readyForQuery: [Function], end: [Function], not
ice: [Function], rowDescription: [Function], dataRow: [Function], portalSuspended: [Function], emptyQuery: [Function], commandComple
te: [Function], parseComplete: [Function], copyInResponse: [Function], copyData: [Function], notification: [Function], error: [Funct
ion: connectedErrorHandler] }, _eventsCount: 18, _maxListeners: undefined, stream: Socket { connecting: false, _hadError: false, _ha
ndle: [TCP], _parent: null, _host: 'localhost', _readableState: [ReadableState], readable: true, _events: [Object], _eventsCount: 5,
 _maxListeners: undefined, _writableState: [WritableState], writable: true, allowHalfOpen: false, _sockname: null, _pendingData: nul
l, _pendingEncoding: '', server: null, _server: null, [Symbol(asyncId)]: 45, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: nul
l, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }, _keepAlive: false, lastBuffer: false, lastOffset: 0, buffer: null, offset:
 1, encoding: 'utf8', parsedStatements: {}, writer: { size: 1024, buffer: <Buffer 51 00 00 00 0b 43 4f 4d 4d 49 54 00 72 65 73 65 74
 44 42 28 29 3b 0d 0a 0d 0a 69 6e 73 65 72 74 20 69 6e 74 6f 20 74 79 70 65 73 20 28 69 73 5f 74 79 ... >, offset: 5, headerPosition
: 0, lastEnd: 0 }, ssl: false, _ending: false, _mode: 0, _emitMessage: false, _reader: { offset: 18, lastChunk: false, chunk: <Buffe
r 43 00 00 00 0b 43 4f 4d 4d 49 54 00 5a 00 00 00 05 49>, chunkLength: 18, headerSize: 1, lengthPadding: -4, header: 90 } }, queryQu
eue: [], binary: false, processID: 3896, secretKey: -690201510, ssl: false, release: [Function], activeQuery: null, readyForQuery: t
rue, hasExecuted: true } +16ms
```
** +++++++++++++++++++++ release in pg-pool err=undefined this.endig=false **
**  tinypg:pool pulse queue +103ms **
**  tinypg:pool no queued requests +4ms **
   ? should be error free

2. Test type functions

------------------------------------------------------------------

tinypg code - tiny.js in transaction
-----------------------------------------------------------------
```javascript
               const release = () => {
                    log('RELEASE transaction client %o', tx_client);
                    tx_client.release = release_ref;
>>>>           tx_client.release(); // no args to release????
                };
```
-----------------------------------------------------------------

pg-pool code i- ndex.js  in release
------------------------------------------------------------------
```javascript
function release (client, err) {
    console.log(`********************* release in pg-pool err=${err} this.endig=${this.ending}`);
  client.release = throwOnRelease
  if (err || this.ending) {
      console.log("*&&&&&&&&&&&&&&&& _remove called");
    this._remove(client)
    this._pulseQueue()
    return
  }
```

-----------------------------------------------------------------

**Comment by joeandaverde** [comment]
I'm not sure we have the same versions of code. For example, client.off is not a function.
pg: 7.4.1
pg-pool: 2.0.3

**Comment by joeandaverde** [comment]
Also worth noting. release is called with a parameter if there was an error. That signals pg-pool to destroy the client.

**Comment by melbardis** [comment]
hi

it seems i have the following versions: (from the package.json file in
each) - and the .off seems to work

pg: 7.4.3
pg-pool: 2.0.3


this was fresh install, since i only started working with node &
postgress about 2 or 3 weeks ago...


regards


eric
