### ISSUE TITLE
SQL Query not found

### ISSUE THREAD

**Issue by efdornbush** [joeandaverde/tinypg#15]
Hello,

I establish my connection:

`
const dbConnection = new TinyPg({
    connection_string: dbUrl,
    root_dir: __dirname + "/queries"
});
`

I call a test query:

`dbConnection.sql("test", {});`

where my file structure is:

/db
--/queries
----test.sql
--connection.js

I receive the error: 

`Error: Sql query with name [test] not found!
    at TinyPg.<anonymous> (/home/web-api/node_modules/tinypg/dist/tiny.js:97:23)
    at Generator.next (<anonymous>)
    at /home/web-api/node_modules/tinypg/dist/tiny.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/web-api/node_modules/tinypg/dist/tiny.js:4:12)
    at /home/web-api/node_modules/tinypg/dist/tiny.js:93:80
    at Object.<anonymous> (/home/web-api/node_modules/tinypg/dist/util.js:28:20)
    at Generator.next (<anonymous>)
    at /home/web-api/node_modules/tinypg/dist/util.js:8:71
    at new Promise (<anonymous>)
`

The TinyPG VS Code plugin can locate test.sql, however.

As far as I can tell, I set everything up correctly. Can you tell me what I'm doing wrong?

**Comment by joeandaverde** [comment]
Try moving the query into a sub folder. It’s looking for test/test.sql. Perhaps an edge case I hadn’t considered. I usually have several folders under the main queries folder. I will look further let me know if that helps.

**Comment by efdornbush** [comment]
I tried that, as well. I got the same error.

**Comment by joeandaverde** [comment]
Is `db` a subfolder to your project? Perhaps you'll need to set the root path to `__dirname +  db/queries`. Double-check the root path is correct.

**Comment by joeandaverde** [comment]
also, to help debug try this: `console.log(dbConnection.sql_files)`

**Comment by efdornbush** [comment]
I'm using typescript so cannot access that field directly, but I did print the entire object...

`console.log(dbConnection);`

`TinyPg {
  events: EventEmitter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false
  },
  error_transformer: [Function: identity],
  options: {
    connection_string: 'postgresql://postgres:postgres@192.168.99.100:5432/webdb?sslmode=disable',
    root_dir: '/home/web-api/dist/db/queries'
  },
  hooks: [],
  pool: Pool {
    _events: [Object: null prototype] { error: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    options: {
      Client: [Function],
      user: 'postgres',
      password: 'postgres',
      host: '192.168.99.100',
      port: 5432,
      database: 'webdb',
      ssl: false,
      keepAlive: undefined,
      connectionTimeoutMillis: undefined,
      idleTimeoutMillis: 10000,
      application_name: undefined,
      statement_timeout: undefined,
      max: 10,
      min: undefined,
      log: [Function]
    },
    log: [Function: debug] {
      namespace: 'tinypg:pool',
      enabled: false,
      useColors: false,
      color: 4,
      destroy: [Function: destroy],
      inspectOpts: {}
    },
    Client: [Function: Client] { Query: [Function: Query] },
    Promise: [Function: Promise],
    _clients: [],
    _idle: [],
    _pendingQueue: [],
    _endCallback: undefined,
    ending: false,
    ended: false,
    [Symbol(kCapture)]: false
  },
  sql_files: [],
  sql_db_calls: {}
}
`
sql_files is an empty array

**Comment by joeandaverde** [comment]
Ah, I see. It's because your js files are being output to a dist folder. The SQL files folder isn't being copied along with the dist. You could either use a relative path or build the .js files next to the .ts files.

**Comment by efdornbush** [comment]
Good catch. What would the relative path look like then?

I could also add a command in my npm build script to copy the sql files to the dist dir.

**Comment by efdornbush** [comment]
I implemented a post-build step to copy the sql files after the typescript compile step using [copyfiles](https://www.npmjs.com/package/copyfiles):

`"postbuild": "copyfiles -u 1 src/**/*.sql dist/"`

But I got the same error as posted above. I then moved the sql file to a directory (test) and am still getting the error...

`Error: Sql query with name [test.test] not found!
    at TinyPg.<anonymous> (/home/web-api/node_modules/tinypg/dist/tiny.js:97:23)
    at Generator.next (<anonymous>)
    at /home/web-api/node_modules/tinypg/dist/tiny.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/web-api/node_modules/tinypg/dist/tiny.js:4:12)
    at /home/web-api/node_modules/tinypg/dist/tiny.js:93:80
    at Object.<anonymous> (/home/web-api/node_modules/tinypg/dist/util.js:28:20)
    at Generator.next (<anonymous>)
    at /home/web-api/node_modules/tinypg/dist/util.js:8:71
    at new Promise (<anonymous>)
`

**Comment by efdornbush** [comment]
The sql_files attribute being logged is still an empty array, as well.

**Comment by efdornbush** [comment]
Fixed it. I also needed to updatemy copyfiles command: 

`"postbuild": "copyfiles -u 1 src/db/**/*.sql dist/"`

Interestingly enough, the sql_files attribute is still an empty array. I called that directly after initializing the TinyPg object

**Comment by abirtley** [comment]
To expand on this, it seems you need to provide an absolute path to the folder where the sql files are stored.

For those using esmodules, `__dirname` is no longer available, but you can [work around this](https://codingbeautydev.com/blog/javascript-dirname-is-not-defined-in-es-module-scope/)

```ts
import { TinyPg } from 'tinypg';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const db = new TinyPg({
  root_dir: path.join(__dirname, 'queries'),
});
```
