### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by cwhiteley** [joeandaverde/tinypg#16]
Tonight I found this module.  Great work.

While giving it a spin, i ran into these two warnings for pg.

(node:6210) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.

(node:6210) DeprecationWarning: Constructing a Query without new is deprecated and will stop working in pg 8.

**Comment by alexmunda** [comment]
Hi @cwhiteley,
Could you please share a code sample and the version of `pg` you are using? I just ran the tinypg tests with a clean `npm i` (pg pinned to `7.12.1` in the package-lock) and did not see any warnings.

Thanks!

**Comment by joeandaverde** [comment]
Thank you for reporting. Does https://github.com/joeandaverde/tinypg/pull/17 address your findings?
