### ISSUE TITLE
[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()

### ISSUE THREAD

**Issue by safaalai** [joeandaverde/tinypg#19]
Code:
`const { TinyPg } = require('tinypg');`
`const db = new TinyPg();`

When I run jest tests on my node.js project, I get :
`console.warn node_modules/tinypg/node_modules/node-uuid/uuid.js:48`
`[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()`

[node-uuid reference](https://www.npmjs.com/package/node-uuid) states that it has been deprecated, "use uuid" instead.  These messages mess up my jest results.  Any chance you can fix it?

**Comment by safaalai** [comment]
Looks like uuid can work as a drop in replacement for node-uuid for a one line fix in tiny.ts.

**Comment by alexmunda** [comment]
Hi @safaalai, thanks for pointing this out. Should be fixed with https://github.com/joeandaverde/tinypg/pull/20.

**Comment by safaalai** [comment]
@alexmunda thanks much and very impressive how fast you fixed this.

**Comment by alexmunda** [comment]
@safaalai no problem, [5.3.0](https://www.npmjs.com/package/tinypg/v/5.3.0) is published now.

**Comment by safaalai** [comment]
Fantastic.  Just tested it and problem has gone away.

P.S. I'm creating a course on Udemy that will be using tinypg to connect to Postgres.   :)

**Comment by alexmunda** [comment]
@safaalai that's great to hear, good luck on your course!
