### ISSUE TITLE
Tiny tries to parse `:00` as a variable in postgres strings

### ISSUE THREAD

**Issue by smerchek** [joeandaverde/tinypg#2]
Given a query that includes the following:

```sql
SELECT '2016-02-15 00:00:00'::timestamptz
```

Tiny gives the following error:

```
Error: Missing expected key [00] on input parameters.
```

Tiny should only try to interpolate variables that are not inside a string or other invalid SQL locations.

**Comment by AndrewRademacher** [comment]
+1

**Comment by joeandaverde** [comment]
+1

**Comment by joeandaverde** [comment]
Fixed here https://github.com/joeandaverde/tinypg/commit/551b60d99cc639053b6bc3462208267f7c52ad09
