### ISSUE TITLE
Getting client according to the connection string

### ISSUE THREAD

**Issue by tihomirmagdic** [joeandaverde/tinypg#8]
I'm interested in how to use TinyPg with different users (different connection string). According to Pg documentation, passed properties to the Pool constructor are passed unchanged to both the node-postgres Client constructor and the node-pool constructor. But if there is any idle client, the pool doesn't check if pool's connection parameters (e.g. user, host, port...) are changed in the meantime or not, Pool just pops the last idle client.

If a new connection string is provided and there’s no client in the Pool with that connection string (connection parameters), a new client must be created regardless of the existence of an idle client in the pool with another connection string.

Maybe the simplest solution is a pool of pools - associated array (an object with properties where each property name is a connection string, and property value is Pool instance). It seems a little heavy.

Light version - In Pool, connect function pops last idle client (if any exists) or creates a new one in the _pendingQueue. Prior to creating a new one, it should check if any idle client has the same connection params and pop that one instead of last one. Although it seems that the issue is more related to Pg-pool than for TinyPg, I still made an issue here too, in case anyone has any solution or advice.

Any other ideas for getting a client from the pool considering the connection string?

**Comment by joeandaverde** [comment]
tinypg@3.0.0-rc1 (on npm) exposes the pool property and adds configuration options for the pool.

**Comment by joeandaverde** [comment]
To understand your intent better. Are you wanting to use the same TinyPg instance to access two different database connections?

In the upcoming version, I've exposed the pool property as well as made node-postgres a peer dependency. 

Does this help?

**Comment by joeandaverde** [comment]
I believe you'll have access to what you need with the most recent changes. Closing this issue.
